Projeto Copa do Mundo/Controllers/JogadorController.cs
using Projeto_Copa_do_Mundo.Models;
using Projeto_Copa_do_Mundo.Models.Data;
using Projeto_Copa_do_Mundo.Utils.Extension;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto_Copa_do_Mundo.Controllers
{
    [Authorize]
    public class JogadorController : Controller
    {
        private readonly UnitOfWork _unitOfWork;

        public JogadorController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Listar()
        {
            List<JogadorVM> lista =
                (from a in _unitOfWork.JogadorRepository.ListarTodos()
                 orderby a.Selecao.Pais descending, a.Nome
                 select new JogadorVM
                 {
                     Id = a.Id,
                     Nascimento = a.Nascimento,
                     Nome = a.Nome,
                     Posicao = a.Posicao,
                     Selecao = new SelecaoVM
                     {
                         Id = a.Selecao.Id,
                         Pais = a.Selecao.Pais,
                         Tecnico = a.Selecao.Tecnico
                     }
                 })
                 .ToList()
                 ;

            return View(lista);
        }

        [HttpGet]
        [ActionName("Cadastrar")]
        public ActionResult NovoJogador()
        {
            ViewData["selecoes"] = GetSelecoes();

            return View();
        }

        private IEnumerable<SelecaoVM> GetSelecoes()
        {
            var listaBD = _unitOfWork
                .SelecaoRepository
                .ListarTodos().Where(a => a.Ativado == true).OrderBy(p => p.Pais);

            var lista =
                from a in listaBD
                select new SelecaoVM
                {
                    Pais = a.Pais,
                    Tecnico = a.Tecnico,
                    Id = a.Id
                };

            return lista;
        }

        [HttpPost, ActionName("Cadastrar"), ValidateAntiForgeryToken]
        public ActionResult NovoJogador(JogadorVM jogador)
        {
            if (!ModelState.IsValid) return View(jogador);

            jogador.Usuario = (Session["usuario"] as UsuarioVM);

            Jogador jogadorBD = new Jogador();

            jogador.CopiarPropriedades(ref jogadorBD);

            _unitOfWork.JogadorRepository.Adicionar(jogadorBD);
            _unitOfWork.Salvar();

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            ViewData["selecoes"] = GetSelecoes();

            var jogadorBD = _unitOfWork.JogadorRepository.Buscar(id);

            JogadorVM jogador = new JogadorVM();

            jogadorBD.CopiarPropriedades(ref jogador);

            return View(jogador);
        }

        [HttpPost]
        public ActionResult Editar(JogadorVM edit)
        {
            if (!ModelState.IsValid)
            {
                TempData["mensagem"] = "Validação pendente";
                return View(edit);
            }



            var jogadorBD = _unitOfWork.JogadorRepository.Buscar(edit.Id);

            jogadorBD.Nome = edit.Nome;
            jogadorBD.Nascimento = edit.Nascimento;
            jogadorBD.Posicao = edit.Posicao;
            jogadorBD.SelecaoId = edit.SelecaoId;
            jogadorBD.DataAlteracao = DateTime.Now;

            _unitOfWork.JogadorRepository.Editar(jogadorBD);
            _unitOfWork.Salvar();
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult ConfirmarRemover(int id)
        {
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Remover(int id)
        {
            return RedirectToAction("Listar");
        }
    }
}

Projeto Copa do Mundo/Controllers/LoginController.cs
using Projeto_Copa_do_Mundo.Models;
using Projeto_Copa_do_Mundo.Models.Data;
using Projeto_Copa_do_Mundo.Utils.Extension;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

namespace Projeto_Copa_do_Mundo.Controllers
{
    public class LoginController : Controller
    {
        private readonly UnitOfWork _unitOfWork;

        public LoginController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost, ActionName("Index")]
        public ActionResult Login(string email, string senha)
        {
            if (!ModelState.IsValid)
            {
                TempData["mensagem"] = "Pendência de formulário";
                return View(new { email = email, senha = senha });
            }
            
            if (string.IsNullOrEmpty(email))
            {
                TempData["mensagem"] = "Email não pode ser vazio";
                return View(new { email = email, senha = senha });
            }

            if (string.IsNullOrEmpty(senha))
            {
                TempData["mensagem"] = "Senha não pode ser vazio";
                return View(new { email = email, senha = senha });
            }

            var usuario = _unitOfWork.UsuarioRepository.Buscar(email);

            if (usuario == null)
            {
                TempData["mensagem"] = "Usuário não encontrado";
                return View(new { email = email, senha = senha });
            }

            if (!usuario.Senha.Equals(senha))
            {
                TempData["mensagem"] = "A senha informada não está correta";
                return View(new { email = email, senha = senha });
            }

            FormsAuthentication.SetAuthCookie(usuario.Nome, false);

            UsuarioVM usuarioVM = new UsuarioVM();
            usuario.CopiarPropriedades(ref usuarioVM);

            Session.Timeout = FormsAuthentication.Timeout.Minutes;
            Session["usuario"] = usuarioVM;
            
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Sair()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index");
        }
    }
}

Projeto Copa do Mundo/Controllers/SelecaoController.cs
using Projeto_Copa_do_Mundo.Models.Data;
using System.Linq;
using System.Web.Mvc;

namespace Projeto_Copa_do_Mundo.Controllers
{ 
    [Authorize]
    public class SelecaoController : Controller
    {
        private readonly UnitOfWork _unitOfWork;

        public SelecaoController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        // GET: Selecao
        public ActionResult Create() => View();

        [HttpPost]
        public ActionResult Create(Selecao selecao)
        {
            if (!ModelState.IsValid)
            {
                TempData["mensagem"] = "Alguma validação pendente";
                return View(selecao);
            }

            selecao.Usuario = (Session["usuario"] as Usuario);

            _unitOfWork.SelecaoRepository.Adicionar(selecao);
            _unitOfWork.Salvar();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id) => View(_unitOfWork.SelecaoRepository.Buscar(id));

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _unitOfWork.SelecaoRepository.Remover(id);
            _unitOfWork.Salvar();
            return RedirectToAction("Index");
        }

        public ActionResult Index() => View(_unitOfWork.SelecaoRepository.ListarTodos().OrderBy(p => p.Pais));

        protected override void Dispose(bool disposing) => _unitOfWork.Dispose();

    }
}

Projeto Copa do Mundo/Views/Shared/_Layout.cshtml
@using Projeto_Copa_do_Mundo.Models;

@{
    var usuario = Session["usuario"] as UsuarioVM;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="dvPagina">
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">
                        <div>
                            <div style="float:left"><img class="logo" alt="Logomarca power" src="~/Content/images/logo.png" width="60" height="60"/></div>
                            <div>

                                Aprendizado....

                                @if (usuario != null)
                                {
                                    <div style="float:right"><br />Olá @usuario.Nome (@Html.ActionLink("Sair", "Sair", "Login"))</div>
                                }
                                else
                                {
                                    <span>Sessão expirou</span>
                                }
                            </div>
                        </div>
                    </p>
                </div>

                <br /><br />
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Cadastrar seleções", "Create", "Selecao", null, new { @class = "xbotao" })</li>
                            <li>@Html.ActionLink("Listar seleções", "Index", "Selecao", null, new { @class = "xbotao" })</li>


                            <li>@Html.ActionLink("Cadastrar jogadores", "Cadastrar", "Jogador", null, new { @class = "xbotao" })</li>
                            <li>@Html.ActionLink("Listar jogadores", "Listar", "Jogador", null, new { @class = "xbotao" })</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>

        <div>@TempData["mensagem"]</div>

        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>

        <footer style="margin-top:200px">
            <div class="content-wrapper">
                <div class="float-right">
                    <ul id="social">
                        <li>
                            <a href="http://facebook.com" class="facebook">Facebook</a>
                        </li>
                        <li>
                            <a href="http://twitter.com" class="twitter">Twitter</a>
                        </li>
                    </ul>
                </div>
                <div class="float-left" style="text-align:center">
                    <p>&copy; @DateTime.Now.Year - Copa do Mundo</p>
                </div>

            </div>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>